config/routes.rb
BucketList::Engine.routes.draw do
  resources :lists
end

app/models/bucket_list/has_lists.rb
module BucketList
	module HasLists
		def has_lists
			has_many :lists, :as => :ownable, :dependent => :destroy, :class_name => "::BucketList::List"
		end
	end
end

app/models/bucket_list/item.rb
module BucketList
  class Item < ActiveRecord::Base
    attr_accessible :completed, :list_id, :name
    belongs_to :list
  end
end

app/models/bucket_list/list.rb
module BucketList
  class List < ActiveRecord::Base
    attr_accessible :name, :ownable_id, :items_attributes
    belongs_to :ownable, :polymorphic => true
    has_many :items

    accepts_nested_attributes_for :items, :reject_if => lambda{ |item| item[:name].blank? }
  end
end

app/controllers/bucket_list/application_controller.rb
module BucketList
  class ApplicationController < ActionController::Base
  end
end

app/controllers/bucket_list/lists_controller.rb
require_dependency "bucket_list/application_controller"

module BucketList
  class ListsController < ApplicationController
    def new
        #check if our list is in a nested resource (determined by a *_id param)
        @ownable = find_ownable
        # if no ownable parameter was found, then we simply create a new list
        if @ownable.nil?
            @list = List.new
        else
            #otherwise we build a new list for the ownable object
            @list = @ownable.lists.build
        end
        #regardless, we build our 3 new items
        3.times{
            @list.items.build
        }
    end
  
    def create
        #check if we are a nested resource
        @ownable = find_ownable
        #if so, we just create the list
        if @ownable.nil?
            @list = List.create(params[:list])
        else
            #otherwise we create the list within our owner
            @list = @ownable.lists.create(params[:list])
        end

        redirect_to list_path(@list)
    end
  
    def index
        #check if we are a nested resource
        @ownable = find_ownable
        #if not, then list all
        if @ownable.nil?
            @lists = List.all
        else
            #otherwise, just return the lists we need
            @lists = @ownable.lists
        end
    end
  
    def show
        #check if we are a nested resource
        @ownable = find_ownable

        #if not, then just find
        if @ownable.nil?
            @list = List.find(params[:id])
        else
            #otherwise look under the context of our ownable object
            @list = @ownable.lists.find(params[:id])
        end
    end
  
    def edit
        #check if we are a nested resource
        @ownable = find_ownable

        #if not, then just find
        if @ownable.nil?
            @list = List.find(params[:id])
        else
            #otherwise look under the context of our ownable object
            @list = @ownable.lists.find(params[:id])
        end

        3.times{
            @list.items.build
        }

    end
  
    def update
        #check if we are a nested resource
        @ownable = find_ownable

        #if not, then just find
        if @ownable.nil?
            @list = List.find(params[:id])
        else
            #otherwise look under the context of our ownable object
            @list = @ownable.lists.find(params[:id])
        end

        @list.update_attributes(params[:list])

        redirect_to list_path(@list)
    end
  
    def delete
         #check if we are a nested resource
        @ownable = find_ownable

        #if not, then just destroy
        if @ownable.nil?
            List.destroy(params[:id])
        else
            #otherwise look under the context of our ownable object and destroy
            @list = @ownable.lists.destroy(params[:id])
        end

        redirect_to :back
    end

    private

    def find_ownable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end
  end
end

app/helpers/bucket_list/application_helper.rb
module BucketList
  module ApplicationHelper
  end
end

app/helpers/bucket_list/bucket_list_helper.rb
module BucketList::BucketListHelper
	def ownable_list_form(ownable, list=nil)
		list = List.new if list.nil?
		render "bucket_list/lists/ownable_list_form", ownable: ownable, list: list
	end

	def ownable_list_list(ownable)
		render "bucket_list/lists/ownable_list_list", :ownable => ownable
	end
end

app/helpers/bucket_list/lists_helper.rb
module BucketList
  module ListsHelper
  end
end

app/views/bucket_list/lists/_form.html.erb
<%= form_for list do |f| %>
	<%= f.label :name %> <%= f.text_field :name %> <br/>
	<h1>Items</h1>
	<%= f.fields_for :items do |fields_builder|%>
		<%= fields_builder.check_box :completed %>
		<%= fields_builder.label :completed %>
		<%= fields_builder.label :name %>
		<%= fields_builder.text_field :name %><br/>
	<% end %>
	 <%= f.submit %>
<% end %>

app/views/bucket_list/lists/_ownable_list_form.html.erb
<%= form_for [ownable,list] do |f| %>
	<%= f.label :name %> <%= f.text_field :name %> <br/>
	<h1>Items</h1>
	<%= f.fields_for :items do |fields_builder|%>
		<%= fields_builder.check_box :completed %>
		<%= fields_builder.label :completed %>
		<%= fields_builder.label :name %>
		<%= fields_builder.text_field :name %><br/>
	<% end %>
	 <%= f.submit %>
<% end %>

app/views/bucket_list/lists/_ownable_list_list.html.erb
<ul>
<% ownable.lists.each do |list| %>
	<% debugger %>
	<li><%= link_to list.name,  bucket_list.list_path(ownable.id, list) %>
		<ul>
		<% list.items.each do |item| %>
			<li><%= item.name %></li>
		<% end %>
		</ul>
	</li>
<% end %>
</ul>

app/views/bucket_list/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/bucket_list/lists/create.html.erb</p>

app/views/bucket_list/lists/delete.html.erb
<h1>Lists#delete</h1>
<p>Find me in app/views/bucket_list/lists/delete.html.erb</p>

app/views/bucket_list/lists/edit.html.erb
<h1>Lists#edit</h1>
<%= render 'form', :list => @list %>

app/views/bucket_list/lists/index.html.erb
<h1>Lists#index</h1>
<ul>
<% @lists.each do |list| %>
	<li><%= link_to list.name, list %> <%= link_to "Edit", edit_list_path(list) %> <%= link_to "Delete", list_path(list), :method => :delete %>
		<ul>
		<% list.items.each do |item| %>
			<li><%= item.name %></li>
		<% end %>
		</ul>
	</li>
<% end %>
</ul>

app/views/bucket_list/lists/new.html.erb
<h1>Lists#new</h1>
<%= render 'form', :list => @list %>

app/views/bucket_list/lists/show.html.erb
<h1>Lists#show</h1>
<%= @list.name %> <%= link_to "Edit", edit_list_path(@list) %> <%= link_to "Delete", list_path(@list), :method => :delete %>
<ul>
<% @list.items.each do |item| %>
	<li><%= item.name %></li>
<% end %>
</ul>

app/views/bucket_list/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/bucket_list/lists/update.html.erb</p>

app/views/layouts/bucket_list/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    "bucket_list/application", :media => "all" %>
  <%= javascript_include_tag "bucket_list/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>